package main

// VisaData - Barcha davlatlar uchun visa ma'lumotlari
var VisaData = map[string]VisaInfo{
	"Schengen": {
		Flag:           "🇪🇺",
		ServicePrice:   "300$",
		VisaType:       "Schengen type C visa",
		VisaFee:        "90 euro + appointment to'lovi",
		ProcessingTime: "15-45 kun",
		Requirements:   "Rasmiy ish joyi bo'lishi shart",
		Details:        "Evropa Ittifoqi davlatlariga kirish uchun visa",
	},
	"USA": {
		Flag:           "🇺🇸",
		ServicePrice:   "300$",
		VisaType:       "1 year Tourist/Business visa",
		VisaFee:        "185 USD",
		ProcessingTime: "Turlicha",
		Requirements:   "Ish joyi rasmiy bo'lishi shart emas. Schengen, UK visalari bo'lsa afzal",
		Details:        "Amerika Qo'shma Shtatlari uchun turist/biznes vizasi",
	},
	"UK": {
		Flag:           "🇬🇧",
		ServicePrice:   "500$",
		VisaType:       "Tourism/Business",
		VisaFee:        "280 USD + 179 USD + 77 GBP",
		ProcessingTime: "Turlicha",
		Requirements:   "Rasmiy ish joyi va maosh karta hisobiga tushishi kerak",
		Details:        "Buyuk Britaniya uchun turist/biznes vizasi",
	},
	"Canada": {
		Flag:           "🇨🇦",
		ServicePrice:   "700$",
		VisaType:       "Tourism Visa",
		VisaFee:        "185 CAD (birinchi), 100 CAD (keyingi)",
		ProcessingTime: "Online topshirish",
		Requirements:   "Bank shot 10,000 USD+, UK/USA/Schengen visa kerak",
		Details:        "Kanada turist vizasi, passport muddati tugagunga qadar",
	},
	"Australia": {
		Flag:           "🇦🇺",
		ServicePrice:   "700$",
		VisaType:       "Tourism E-visa",
		VisaFee:        "195 AUD",
		ProcessingTime: "Max 1 oy",
		Requirements:   "Bank shot 25,000-30,000 USD",
		Details:        "3/6/12 oylik Multi visa",
	},
	"New Zealand": {
		Flag:           "🇳🇿",
		ServicePrice:   "700$",
		VisaType:       "Visitor E-visa",
		VisaFee:        "441 NZD",
		ProcessingTime: "Online",
		Requirements:   "Australia visa bo'lishi shart",
		Details:        "Yangi Zelandiya tashrif vizasi",
	},
	"Japan": {
		Flag:           "🇯🇵",
		ServicePrice:   "300$",
		VisaType:       "Tourism",
		VisaFee:        "Bepul",
		ProcessingTime: "5 ish kuni",
		Requirements:   "Rasmiy ish joyi, Bank shot va abarotka",
		Details:        "3 oylik Single entry visa",
	},
	"Brazil": {
		Flag:           "🇧🇷",
		ServicePrice:   "300$",
		VisaType:       "Tourism",
		VisaFee:        "8800 ruble",
		ProcessingTime: "10 ish kuni",
		Requirements:   "Bank shot va abarotka. Ish joyi rasmiy bo'lishi shart emas",
		Details:        "1 yillik Multi visa, travel history kerak emas",
	},
	"Saudi Arabia": {
		Flag:           "🇸🇦",
		ServicePrice:   "BEPUL",
		VisaType:       "Tourism E-visa",
		VisaFee:        "110 USD",
		ProcessingTime: "1 ish kuni",
		Requirements:   "Minimal",
		Details:        "1 yillik Multi visa",
	},
	"India": {
		Flag:           "🇮🇳",
		ServicePrice:   "100$",
		VisaType:       "Tourism E-visa",
		VisaFee:        "41 USD",
		ProcessingTime: "Tez",
		Requirements:   "Bank shot, ish joyi",
		Details:        "1 yillik Multi visa",
	},
	"South Africa": {
		Flag:           "🇿🇦",
		ServicePrice:   "500$",
		VisaType:       "Tourism",
		VisaFee:        "33 euro",
		ProcessingTime: "5 ish kuni",
		Requirements:   "Bank shot, abarotka, ish joyi rasmiy bo'lishi shart emas",
		Details:        "3 oylik single/multi visa, Ankara elchixonasi",
	},
	"Seychelles": {
		Flag:           "🇸🇨",
		ServicePrice:   "100$",
		VisaType:       "ETA",
		VisaFee:        "30 euro",
		ProcessingTime: "Tez",
		Requirements:   "Sug'urta kerak",
		Details:        "3 oylik single entry",
	},
	"Uganda": {
		Flag:           "🇺🇬",
		ServicePrice:   "300$",
		VisaType:       "Tourism E-visa",
		VisaFee:        "50 USD (single), 100 USD (multi)",
		ProcessingTime: "2-4 ish kuni",
		Requirements:   "Sug'urta, barmoq izi topshirish",
		Details:        "3 oylik visa",
	},
	"Kuwait": {
		Flag:           "🇰🇼",
		ServicePrice:   "100$",
		VisaType:       "Tourism",
		VisaFee:        "10-30 USD",
		ProcessingTime: "3-5 ish kuni",
		Requirements:   "Rasmiy ish joyi, sug'urta, Bank shot",
		Details:        "1 oylik single/multi",
	},
	"Bahrain": {
		Flag:           "🇧🇭",
		ServicePrice:   "100$",
		VisaType:       "Tourism E-visa",
		VisaFee:        "45 USD",
		ProcessingTime: "1 kun",
		Requirements:   "UAE/UK/USA/Saudi/Schengen visa kerak",
		Details:        "3 oylik Multi visa",
	},
	"Israel": {
		Flag:           "🇮🇱",
		ServicePrice:   "500$",
		VisaType:       "Tourism",
		VisaFee:        "864,000 UZS",
		ProcessingTime: "Turlicha",
		Requirements:   "Rasmiy ish joyi, Bank shot",
		Details:        "3 oylik Single entry",
	},
	"Pakistan": {
		Flag:           "🇵🇰",
		ServicePrice:   "100$",
		VisaType:       "Tourist E-visa",
		VisaFee:        "BEPUL",
		ProcessingTime: "Tez",
		Requirements:   "Bank shot",
		Details:        "3 oylik Multi visa",
	},
	"Vietnam": {
		Flag:           "🇻🇳",
		ServicePrice:   "100$",
		VisaType:       "Tourism E-visa",
		VisaFee:        "25 USD (single), 50 USD (multi)",
		ProcessingTime: "3 ish kuni",
		Requirements:   "Rasmiy ish joyi kerak emas",
		Details:        "3 oylik visa",
	},
	"Albania": {
		Flag:           "🇦🇱",
		ServicePrice:   "300$",
		VisaType:       "Tourism E-visa",
		VisaFee:        "30 euro (single), 100 euro (multi)",
		ProcessingTime: "15-30 ish kuni",
		Requirements:   "Bank shot, abarotka, rasmiy ish joyi",
		Details:        "180 kunlik visa",
	},
	"Taiwan": {
		Flag:           "🇹🇼",
		ServicePrice:   "300$",
		VisaType:       "Tourism",
		VisaFee:        "50 USD (single), 100 USD (multi)",
		ProcessingTime: "5 ish kuni",
		Requirements:   "Bank shot, ish joyi",
		Details:        "Moskva va Ankara elchixonalari",
	},
	"Turkey": {
		Flag:           "🇹🇷",
		ServicePrice:   "100$",
		VisaType:       "Tourism E-visa",
		VisaFee:        "50 USD",
		ProcessingTime: "1 kun",
		Requirements:   "Minimal",
		Details:        "90 kunlik Multi visa",
	},
	"UAE": {
		Flag:           "🇦🇪",
		ServicePrice:   "200$",
		VisaType:       "Tourism",
		VisaFee:        "350 AED",
		ProcessingTime: "3-5 ish kuni",
		Requirements:   "Bank shot, sug'urta",
		Details:        "30/90 kunlik visa",
	},
	"Qatar": {
		Flag:           "🇶🇦",
		ServicePrice:   "200$",
		VisaType:       "Tourism E-visa",
		VisaFee:        "100 QAR",
		ProcessingTime: "2-3 ish kuni",
		Requirements:   "Sug'urta, hotel booking",
		Details:        "30 kunlik Single entry",
	},
	"Oman": {
		Flag:           "🇴🇲",
		ServicePrice:   "150$",
		VisaType:       "Tourism E-visa",
		VisaFee:        "20 OMR",
		ProcessingTime: "1-2 ish kuni",
		Requirements:   "Sug'urta kerak",
		Details:        "30 kunlik Single entry",
	},
	"Jordan": {
		Flag:           "🇯🇴",
		ServicePrice:   "200$",
		VisaType:       "Tourism",
		VisaFee:        "40 JOD",
		ProcessingTime: "Tez",
		Requirements:   "Bank shot, sug'urta",
		Details:        "30 kunlik Single entry",
	},
	"Egypt": {
		Flag:           "🇪🇬",
		ServicePrice:   "150$",
		VisaType:       "Tourism E-visa",
		VisaFee:        "25 USD",
		ProcessingTime: "1-3 ish kuni",
		Requirements:   "Sug'urta, hotel booking",
		Details:        "30 kunlik Single entry",
	},
	"Morocco": {
		Flag:           "🇲🇦",
		ServicePrice:   "200$",
		VisaType:       "Tourism",
		VisaFee:        "99 EUR",
		ProcessingTime: "5-10 ish kuni",
		Requirements:   "Bank shot, hotel booking",
		Details:        "90 kunlik Single entry",
	},
	"Tunisia": {
		Flag:           "🇹🇳",
		ServicePrice:   "150$",
		VisaType:       "Tourism",
		VisaFee:        "60 EUR",
		ProcessingTime: "3-5 ish kuni",
		Requirements:   "Bank shot, sug'urta",
		Details:        "90 kunlik Single entry",
	},
	"Kenya": {
		Flag:           "🇰🇪",
		ServicePrice:   "200$",
		VisaType:       "Tourism E-visa",
		VisaFee:        "51 USD",
		ProcessingTime: "2-5 ish kuni",
		Requirements:   "Sug'urta, sariq isitma vaksinasi",
		Details:        "90 kunlik Single entry",
	},
	"Tanzania": {
		Flag:           "🇹🇿",
		ServicePrice:   "200$",
		VisaType:       "Tourism E-visa",
		VisaFee:        "50 USD",
		ProcessingTime: "3-7 ish kuni",
		Requirements:   "Sug'urta, sariq isitma vaksinasi",
		Details:        "90 kunlik Single entry",
	},
	"Ethiopia": {
		Flag:           "🇪🇹",
		ServicePrice:   "200$",
		VisaType:       "Tourism E-visa",
		VisaFee:        "52 USD",
		ProcessingTime: "3-5 ish kuni",
		Requirements:   "Sug'urta, sariq isitma vaksinasi",
		Details:        "90 kunlik Single entry",
	},
}
